
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "--http_port", "8222"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s


  app:
    build: .
    ports:
      - "8000:8000"  # Add this
    depends_on:
      - nats


  test_integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    working_dir: /app/test